ccnu:
    build: .
    env_file:
        - ccnu.env
    command: python server.py
    ports:
        - "3000:5000"
    links:
        - redis1

redis1:
    image: redis
    command: redis-server --port 6384  # 缓存
    ports:
        - "7384:6384"
